// WARNING: this is an autogenerated file. Any change might be overwritten!

#include "intl.h"
#include <tuple>
namespace spec {

using mstring = const char*;
using mapping = std::tuple<mstring, mstring, mstring>;

namespace mcat {	
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAccessibility = N_("Accessibility");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAccessories = N_("Accessories");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAudio = N_("Audio");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAudioVideo = N_("AudioVideo");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDevelopment = N_("Development");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xEditors = N_("Editors");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xEducation = N_("Education");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xGame = N_("Game");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xGraphics = N_("Graphics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMultimedia = N_("Multimedia");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xNetwork = N_("Network");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xOffice = N_("Office");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xOther = N_("Other");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xScience = N_("Science");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xScreensavers = N_("Screensavers");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSettings = N_("Settings");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSystem = N_("System");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xUtility = N_("Utility");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xVideo = N_("Video");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xWINE = N_("WINE");

	const mstring sall[] = {
		xAccessibility,
		xAccessories,
		xAudio,
		xAudioVideo,
		xDevelopment,
		xEditors,
		xEducation,
		xGame,
		xGraphics,
		xMultimedia,
		xNetwork,
		xOffice,
		xOther,
		xScience,
		xScreensavers,
		xSettings,
		xSystem,
		xUtility,
		xVideo,
		xWINE
	};
}

namespace scat {
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xBuilding = N_("Building");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDebugger = N_("Debugger");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xIDE = N_("IDE");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xGUIDesigner = N_("GUIDesigner");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xProfiling = N_("Profiling");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xRevisionControl = N_("RevisionControl");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTranslation = N_("Translation");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xCalendar = N_("Calendar");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xContactManagement = N_("ContactManagement");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDatabase = N_("Database");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDictionary = N_("Dictionary");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xChart = N_("Chart");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xEmail = N_("Email");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFinance = N_("Finance");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFlowChart = N_("FlowChart");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPDA = N_("PDA");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xProjectManagement = N_("ProjectManagement");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPresentation = N_("Presentation");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSpreadsheet = N_("Spreadsheet");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xWordProcessor = N_("WordProcessor");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto x2DGraphics = N_("2DGraphics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xVectorGraphics = N_("VectorGraphics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xRasterGraphics = N_("RasterGraphics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto x3DGraphics = N_("3DGraphics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xScanning = N_("Scanning");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xOCR = N_("OCR");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPhotography = N_("Photography");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPublishing = N_("Publishing");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xViewer = N_("Viewer");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTextTools = N_("TextTools");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDesktopSettings = N_("DesktopSettings");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xHardwareSettings = N_("HardwareSettings");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPrinting = N_("Printing");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPackageManager = N_("PackageManager");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDialup = N_("Dialup");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xInstantMessaging = N_("InstantMessaging");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xChat = N_("Chat");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xIRCClient = N_("IRCClient");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFeed = N_("Feed");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFileTransfer = N_("FileTransfer");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xHamRadio = N_("HamRadio");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xNews = N_("News");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xP2P = N_("P2P");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xRemoteAccess = N_("RemoteAccess");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTelephony = N_("Telephony");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTelephonyTools = N_("TelephonyTools");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xVideoConference = N_("VideoConference");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xWebBrowser = N_("WebBrowser");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xWebDevelopment = N_("WebDevelopment");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMidi = N_("Midi");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMixer = N_("Mixer");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSequencer = N_("Sequencer");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTuner = N_("Tuner");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTV = N_("TV");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAudioVideoEditing = N_("AudioVideoEditing");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPlayer = N_("Player");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xRecorder = N_("Recorder");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDiscBurning = N_("DiscBurning");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xActionGame = N_("ActionGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAdventureGame = N_("AdventureGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xArcadeGame = N_("ArcadeGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xBoardGame = N_("BoardGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xBlocksGame = N_("BlocksGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xCardGame = N_("CardGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xKidsGame = N_("KidsGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xLogicGame = N_("LogicGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xRolePlaying = N_("RolePlaying");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xShooter = N_("Shooter");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSimulation = N_("Simulation");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSportsGame = N_("SportsGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xStrategyGame = N_("StrategyGame");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xArt = N_("Art");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xConstruction = N_("Construction");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMusic = N_("Music");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xLanguages = N_("Languages");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xArtificialIntelligence = N_("ArtificialIntelligence");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAstronomy = N_("Astronomy");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xBiology = N_("Biology");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xChemistry = N_("Chemistry");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xComputerScience = N_("ComputerScience");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDataVisualization = N_("DataVisualization");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xEconomy = N_("Economy");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xElectricity = N_("Electricity");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xGeography = N_("Geography");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xGeology = N_("Geology");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xGeoscience = N_("Geoscience");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xHistory = N_("History");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xHumanities = N_("Humanities");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xImageProcessing = N_("ImageProcessing");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xLiterature = N_("Literature");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMaps = N_("Maps");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMath = N_("Math");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xNumericalAnalysis = N_("NumericalAnalysis");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMedicalSoftware = N_("MedicalSoftware");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xPhysics = N_("Physics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xRobotics = N_("Robotics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSpirituality = N_("Spirituality");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSports = N_("Sports");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xParallelComputing = N_("ParallelComputing");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAmusement = N_("Amusement");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xArchiving = N_("Archiving");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xCompression = N_("Compression");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xElectronics = N_("Electronics");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xEmulator = N_("Emulator");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xEngineering = N_("Engineering");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFileTools = N_("FileTools");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFileManager = N_("FileManager");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTerminalEmulator = N_("TerminalEmulator");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xFilesystem = N_("Filesystem");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xMonitor = N_("Monitor");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xSecurity = N_("Security");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAccessibility = N_("Accessibility");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xCalculator = N_("Calculator");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xClock = N_("Clock");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xTextEditor = N_("TextEditor");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xDocumentation = N_("Documentation");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xAdult = N_("Adult");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xCore = N_("Core");
	
	// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
	const auto xConsoleOnly = N_("ConsoleOnly");
}

static mapping subcat_to_maincat[] = {

// statically presorted list of sub category mapping. See fdomenu.cc for details.
	{ scat::x2DGraphics, mcat::xGraphics, nullptr },
	{ scat::x3DGraphics, mcat::xGraphics, nullptr },
	{ scat::xAccessibility, mcat::xSettings, nullptr },
	{ scat::xAccessibility, mcat::xUtility, nullptr },
	{ scat::xActionGame, mcat::xGame, nullptr },
	{ scat::xAdult, nullptr, nullptr },
	{ scat::xAdventureGame, mcat::xGame, nullptr },
	{ scat::xAmusement, nullptr, nullptr },
	{ scat::xArcadeGame, mcat::xGame, nullptr },
	{ scat::xArchiving, mcat::xUtility, nullptr },
	{ scat::xArt, mcat::xEducation, nullptr },
	{ scat::xArt, mcat::xScience, nullptr },
	{ scat::xArtificialIntelligence, mcat::xEducation, nullptr },
	{ scat::xArtificialIntelligence, mcat::xScience, nullptr },
	{ scat::xAstronomy, mcat::xEducation, nullptr },
	{ scat::xAstronomy, mcat::xScience, nullptr },
	{ scat::xAudioVideoEditing, mcat::xAudio, nullptr },
	{ scat::xAudioVideoEditing, mcat::xVideo, nullptr },
	{ scat::xBiology, mcat::xEducation, nullptr },
	{ scat::xBiology, mcat::xScience, nullptr },
	{ scat::xBlocksGame, mcat::xGame, nullptr },
	{ scat::xBoardGame, mcat::xGame, nullptr },
	{ scat::xBuilding, mcat::xDevelopment, nullptr },
	{ scat::xCalculator, mcat::xUtility, nullptr },
	{ scat::xCalendar, mcat::xOffice, nullptr },
	{ scat::xCardGame, mcat::xGame, nullptr },
	{ scat::xChart, mcat::xOffice, nullptr },
	{ scat::xChat, mcat::xNetwork, nullptr },
	{ scat::xChemistry, mcat::xEducation, nullptr },
	{ scat::xChemistry, mcat::xScience, nullptr },
	{ scat::xClock, mcat::xUtility, nullptr },
	{ scat::xCompression, nullptr, scat::xArchiving },
	{ scat::xCompression, mcat::xUtility, nullptr },
	{ scat::xComputerScience, mcat::xEducation, nullptr },
	{ scat::xComputerScience, mcat::xScience, nullptr },
	{ scat::xConsoleOnly, nullptr, nullptr },
	{ scat::xConstruction, mcat::xEducation, nullptr },
	{ scat::xConstruction, mcat::xScience, nullptr },
	{ scat::xContactManagement, mcat::xOffice, nullptr },
	{ scat::xCore, nullptr, nullptr },
	{ scat::xDataVisualization, mcat::xEducation, nullptr },
	{ scat::xDataVisualization, mcat::xScience, nullptr },
	{ scat::xDatabase, mcat::xAudio, nullptr },
	{ scat::xDatabase, mcat::xDevelopment, nullptr },
	{ scat::xDatabase, mcat::xOffice, nullptr },
	{ scat::xDatabase, mcat::xVideo, nullptr },
	{ scat::xDebugger, mcat::xDevelopment, nullptr },
	{ scat::xDesktopSettings, mcat::xSettings, nullptr },
	{ scat::xDialup, mcat::xNetwork, nullptr },
	{ scat::xDictionary, mcat::xOffice, nullptr },
	{ scat::xDictionary, nullptr, scat::xTextTools },
	{ scat::xDiscBurning, mcat::xAudio, nullptr },
	{ scat::xDiscBurning, mcat::xVideo, nullptr },
	{ scat::xDocumentation, nullptr, nullptr },
	{ scat::xEconomy, mcat::xEducation, nullptr },
	{ scat::xEconomy, mcat::xScience, nullptr },
	{ scat::xElectricity, mcat::xEducation, nullptr },
	{ scat::xElectricity, mcat::xScience, nullptr },
	{ scat::xElectronics, nullptr, nullptr },
	{ scat::xEmail, mcat::xNetwork, nullptr },
	{ scat::xEmail, mcat::xOffice, nullptr },
	{ scat::xEmulator, mcat::xGame, nullptr },
	{ scat::xEmulator, mcat::xSystem, nullptr },
	{ scat::xEngineering, nullptr, nullptr },
	{ scat::xFeed, mcat::xNetwork, nullptr },
	{ scat::xFileManager, nullptr, scat::xFileTools },
	{ scat::xFileManager, mcat::xSystem, nullptr },
	{ scat::xFileTools, mcat::xSystem, nullptr },
	{ scat::xFileTools, mcat::xUtility, nullptr },
	{ scat::xFileTransfer, mcat::xNetwork, nullptr },
	{ scat::xFilesystem, mcat::xSystem, nullptr },
	{ scat::xFinance, mcat::xOffice, nullptr },
	{ scat::xFlowChart, mcat::xOffice, nullptr },
	{ scat::xGUIDesigner, mcat::xDevelopment, nullptr },
	{ scat::xGeography, mcat::xEducation, nullptr },
	{ scat::xGeography, mcat::xScience, nullptr },
	{ scat::xGeology, mcat::xEducation, nullptr },
	{ scat::xGeology, mcat::xScience, nullptr },
	{ scat::xGeoscience, mcat::xEducation, nullptr },
	{ scat::xGeoscience, mcat::xScience, nullptr },
	{ scat::xHamRadio, mcat::xAudio, nullptr },
	{ scat::xHamRadio, mcat::xNetwork, nullptr },
	{ scat::xHardwareSettings, mcat::xSettings, nullptr },
	{ scat::xHistory, mcat::xEducation, nullptr },
	{ scat::xHistory, mcat::xScience, nullptr },
	{ scat::xHumanities, mcat::xEducation, nullptr },
	{ scat::xHumanities, mcat::xScience, nullptr },
	{ scat::xIDE, mcat::xDevelopment, nullptr },
	{ scat::xIRCClient, mcat::xNetwork, nullptr },
	{ scat::xImageProcessing, mcat::xEducation, nullptr },
	{ scat::xImageProcessing, mcat::xScience, nullptr },
	{ scat::xInstantMessaging, mcat::xNetwork, nullptr },
	{ scat::xKidsGame, mcat::xGame, nullptr },
	{ scat::xLanguages, mcat::xEducation, nullptr },
	{ scat::xLanguages, mcat::xScience, nullptr },
	{ scat::xLiterature, mcat::xEducation, nullptr },
	{ scat::xLiterature, mcat::xScience, nullptr },
	{ scat::xLogicGame, mcat::xGame, nullptr },
	{ scat::xMaps, mcat::xEducation, nullptr },
	{ scat::xMaps, mcat::xScience, nullptr },
	{ scat::xMaps, mcat::xUtility, nullptr },
	{ scat::xMath, mcat::xEducation, nullptr },
	{ scat::xMath, mcat::xScience, nullptr },
	{ scat::xMedicalSoftware, mcat::xEducation, nullptr },
	{ scat::xMedicalSoftware, mcat::xScience, nullptr },
	{ scat::xMidi, mcat::xAudio, nullptr },
	{ scat::xMidi, mcat::xVideo, nullptr },
	{ scat::xMixer, mcat::xAudio, nullptr },
	{ scat::xMixer, mcat::xVideo, nullptr },
	{ scat::xMonitor, mcat::xNetwork, nullptr },
	{ scat::xMonitor, mcat::xSystem, nullptr },
	{ scat::xMusic, mcat::xAudio, nullptr },
	{ scat::xMusic, mcat::xEducation, nullptr },
	{ scat::xMusic, mcat::xVideo, nullptr },
	{ scat::xNews, mcat::xNetwork, nullptr },
	{ scat::xNumericalAnalysis, mcat::xEducation, nullptr },
	{ scat::xNumericalAnalysis, nullptr, scat::xMath },
	{ scat::xNumericalAnalysis, mcat::xScience, nullptr },
	{ scat::xOCR, mcat::xGraphics, nullptr },
	{ scat::xOCR, nullptr, scat::xScanning },
	{ scat::xP2P, mcat::xNetwork, nullptr },
	{ scat::xPDA, mcat::xOffice, nullptr },
	{ scat::xPackageManager, mcat::xSettings, nullptr },
	{ scat::xParallelComputing, nullptr, scat::xComputerScience },
	{ scat::xParallelComputing, mcat::xEducation, nullptr },
	{ scat::xParallelComputing, mcat::xScience, nullptr },
	{ scat::xPhotography, mcat::xGraphics, nullptr },
	{ scat::xPhotography, mcat::xOffice, nullptr },
	{ scat::xPhysics, mcat::xEducation, nullptr },
	{ scat::xPhysics, mcat::xScience, nullptr },
	{ scat::xPlayer, mcat::xAudio, nullptr },
	{ scat::xPlayer, mcat::xVideo, nullptr },
	{ scat::xPresentation, mcat::xOffice, nullptr },
	{ scat::xPrinting, nullptr, scat::xHardwareSettings },
	{ scat::xPrinting, mcat::xSettings, nullptr },
	{ scat::xProfiling, mcat::xDevelopment, nullptr },
	{ scat::xProjectManagement, mcat::xDevelopment, nullptr },
	{ scat::xProjectManagement, mcat::xOffice, nullptr },
	{ scat::xPublishing, mcat::xGraphics, nullptr },
	{ scat::xPublishing, mcat::xOffice, nullptr },
	{ scat::xRasterGraphics, nullptr, scat::x2DGraphics },
	{ scat::xRasterGraphics, mcat::xGraphics, nullptr },
	{ scat::xRecorder, mcat::xAudio, nullptr },
	{ scat::xRecorder, mcat::xVideo, nullptr },
	{ scat::xRemoteAccess, mcat::xNetwork, nullptr },
	{ scat::xRevisionControl, mcat::xDevelopment, nullptr },
	{ scat::xRobotics, mcat::xEducation, nullptr },
	{ scat::xRobotics, mcat::xScience, nullptr },
	{ scat::xRolePlaying, mcat::xGame, nullptr },
	{ scat::xScanning, mcat::xGraphics, nullptr },
	{ scat::xSecurity, mcat::xSettings, nullptr },
	{ scat::xSecurity, mcat::xSystem, nullptr },
	{ scat::xSequencer, mcat::xAudio, nullptr },
	{ scat::xSequencer, mcat::xVideo, nullptr },
	{ scat::xShooter, mcat::xGame, nullptr },
	{ scat::xSimulation, mcat::xGame, nullptr },
	{ scat::xSpirituality, mcat::xEducation, nullptr },
	{ scat::xSpirituality, mcat::xScience, nullptr },
	{ scat::xSpirituality, mcat::xUtility, nullptr },
	{ scat::xSports, mcat::xEducation, nullptr },
	{ scat::xSports, mcat::xScience, nullptr },
	{ scat::xSportsGame, mcat::xGame, nullptr },
	{ scat::xSpreadsheet, mcat::xOffice, nullptr },
	{ scat::xStrategyGame, mcat::xGame, nullptr },
	{ scat::xTV, mcat::xAudio, nullptr },
	{ scat::xTV, mcat::xVideo, nullptr },
	{ scat::xTelephony, mcat::xNetwork, nullptr },
	{ scat::xTelephonyTools, mcat::xUtility, nullptr },
	{ scat::xTerminalEmulator, mcat::xSystem, nullptr },
	{ scat::xTextEditor, mcat::xUtility, nullptr },
	{ scat::xTextTools, mcat::xUtility, nullptr },
	{ scat::xTranslation, mcat::xDevelopment, nullptr },
	{ scat::xTuner, mcat::xAudio, nullptr },
	{ scat::xTuner, mcat::xVideo, nullptr },
	{ scat::xVectorGraphics, nullptr, scat::x2DGraphics },
	{ scat::xVectorGraphics, mcat::xGraphics, nullptr },
	{ scat::xVideoConference, mcat::xNetwork, nullptr },
	{ scat::xViewer, mcat::xGraphics, nullptr },
	{ scat::xViewer, mcat::xOffice, nullptr },
	{ scat::xWebBrowser, mcat::xNetwork, nullptr },
	{ scat::xWebDevelopment, mcat::xDevelopment, nullptr },
	{ scat::xWebDevelopment, mcat::xNetwork, nullptr },
	{ scat::xWordProcessor, mcat::xOffice, nullptr },

	};
}
