// WARNING: this is an autogenerated file. Any change might be overwritten!

#include "intl.h"
namespace spec {
const char* ANY[] = { "", "|", nullptr };
const char* AudioVideo[] = { "AudioVideo", "|", nullptr };
const char* AudioVideoAudio[] = { "AudioVideo", "Audio", "|", nullptr };
const char* AudioVideoVideo[] = { "AudioVideo", "Video", "|", nullptr };
const char* AudioVideoorEducation[] = { "AudioVideo", "|", "Education", "|", nullptr };
const char* AudioorVideoorAudioVideo[] = { "Audio", "|", "Video", "|", "AudioVideo", "|", nullptr };
const char* Development[] = { "Development", "|", nullptr };
const char* EducationComputerScienceorScienceComputerScience[] = { "Education", "ComputerScience", "|", "Science", "ComputerScience", "|", nullptr };
const char* EducationMathorScienceMath[] = { "Education", "Math", "|", "Science", "Math", "|", nullptr };
const char* EducationorScience[] = { "Education", "|", "Science", "|", nullptr };
const char* EducationorScienceorUtility[] = { "Education", "|", "Science", "|", "Utility", "|", nullptr };
const char* Game[] = { "Game", "|", nullptr };
const char* Graphics[] = { "Graphics", "|", nullptr };
const char* Graphics2DGraphics[] = { "Graphics", "2DGraphics", "|", nullptr };
const char* GraphicsScanning[] = { "Graphics", "Scanning", "|", nullptr };
const char* GraphicsorOffice[] = { "Graphics", "|", "Office", "|", nullptr };
const char* Network[] = { "Network", "|", nullptr };
const char* NetworkorAudio[] = { "Network", "|", "Audio", "|", nullptr };
const char* NetworkorDevelopment[] = { "Network", "|", "Development", "|", nullptr };
const char* Office[] = { "Office", "|", nullptr };
const char* OfficeorDevelopment[] = { "Office", "|", "Development", "|", nullptr };
const char* OfficeorDevelopmentorAudioVideo[] = { "Office", "|", "Development", "|", "AudioVideo", "|", nullptr };
const char* OfficeorNetwork[] = { "Office", "|", "Network", "|", nullptr };
const char* OfficeorTextTools[] = { "Office", "|", "TextTools", "|", nullptr };
const char* Settings[] = { "Settings", "|", nullptr };
const char* SettingsHardwareSettings[] = { "Settings", "HardwareSettings", "|", nullptr };
const char* SettingsorSystem[] = { "Settings", "|", "System", "|", nullptr };
const char* SettingsorUtility[] = { "Settings", "|", "Utility", "|", nullptr };
const char* System[] = { "System", "|", nullptr };
const char* SystemFileTools[] = { "System", "FileTools", "|", nullptr };
const char* SystemorGame[] = { "System", "|", "Game", "|", nullptr };
const char* SystemorNetwork[] = { "System", "|", "Network", "|", nullptr };
const char* Utility[] = { "Utility", "|", nullptr };
const char* UtilityArchiving[] = { "Utility", "Archiving", "|", nullptr };
const char* UtilityorSystem[] = { "Utility", "|", "System", "|", nullptr };

// statically presorted list of categories. See fdomenu.cc for details.
const tStaticMenuDescription menuinfo[] =
{
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics
    { N_("2DGraphics"), "folder", (const char**) &Graphics},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics
    { N_("3DGraphics"), "folder", (const char**) &Graphics},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings or Utility
    { N_("Accessibility"), "folder", (const char**) &SettingsorUtility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings or Utility
    { N_("Accessibility"), "folder", (const char**) &SettingsorUtility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Accessories"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("ActionGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Adult"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("AdventureGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Amusement"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("ArcadeGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility
    { N_("Archiving"), "folder", (const char**) &Utility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Art"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("ArtificialIntelligence"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Astronomy"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Audio"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("AudioVideo"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Audio or Video or AudioVideo
    { N_("AudioVideoEditing"), "folder", (const char**) &AudioorVideoorAudioVideo},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Biology"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("BlocksGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("BoardGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("Building"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility
    { N_("Calculator"), "folder", (const char**) &Utility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("Calendar"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("CardGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("Chart"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("Chat"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Chemistry"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility
    { N_("Clock"), "folder", (const char**) &Utility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility;Archiving
    { N_("Compression"), "folder", (const char**) &UtilityArchiving},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("ComputerScience"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Construction"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("ContactManagement"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Core"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("DataVisualization"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office or Development or AudioVideo
    { N_("Database"), "folder", (const char**) &OfficeorDevelopmentorAudioVideo},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("Debugger"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings
    { N_("DesktopSettings"), "folder", (const char**) &Settings},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Development"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("Dialup"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office or TextTools
    { N_("Dictionary"), "folder", (const char**) &OfficeorTextTools},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo
    { N_("DiscBurning"), "folder", (const char**) &AudioVideo},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Documentation"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Economy"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Editors"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Education"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Electricity"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Electronics"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office or Network
    { N_("Email"), "folder", (const char**) &OfficeorNetwork},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: System or Game
    { N_("Emulator"), "folder", (const char**) &SystemorGame},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Engineering"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("Feed"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: System;FileTools
    { N_("FileManager"), "folder", (const char**) &SystemFileTools},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility or System
    { N_("FileTools"), "folder", (const char**) &UtilityorSystem},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("FileTransfer"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: System
    { N_("Filesystem"), "folder", (const char**) &System},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("Finance"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("FlowChart"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("GUIDesigner"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Game"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Geography"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Geology"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Geoscience"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Graphics"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network or Audio
    { N_("HamRadio"), "folder", (const char**) &NetworkorAudio},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings
    { N_("HardwareSettings"), "folder", (const char**) &Settings},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("History"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Humanities"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("IDE"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("IRCClient"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("ImageProcessing"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("InstantMessaging"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("KidsGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Languages"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Literature"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("LogicGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science or Utility
    { N_("Maps"), "folder", (const char**) &EducationorScienceorUtility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Math"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("MedicalSoftware"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo;Audio
    { N_("Midi"), "folder", (const char**) &AudioVideoAudio},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo;Audio
    { N_("Mixer"), "folder", (const char**) &AudioVideoAudio},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: System or Network
    { N_("Monitor"), "folder", (const char**) &SystemorNetwork},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Motif"), "folder", (const char**) &ANY},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Multimedia"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo or Education
    { N_("Music"), "folder", (const char**) &AudioVideoorEducation},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Network"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("News"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education;Math or Science;Math
    { N_("NumericalAnalysis"), "folder", (const char**) &EducationMathorScienceMath},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics;Scanning
    { N_("OCR"), "folder", (const char**) &GraphicsScanning},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Office"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Other"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("P2P"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("PDA"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings
    { N_("PackageManager"), "folder", (const char**) &Settings},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education;ComputerScience or Science;ComputerScience
    { N_("ParallelComputing"), "folder", (const char**) &EducationComputerScienceorScienceComputerScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics or Office
    { N_("Photography"), "folder", (const char**) &GraphicsorOffice},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Physics"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Audio or Video or AudioVideo
    { N_("Player"), "folder", (const char**) &AudioorVideoorAudioVideo},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("Presentation"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings;HardwareSettings
    { N_("Printing"), "folder", (const char**) &SettingsHardwareSettings},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("Profiling"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office or Development
    { N_("ProjectManagement"), "folder", (const char**) &OfficeorDevelopment},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics or Office
    { N_("Publishing"), "folder", (const char**) &GraphicsorOffice},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics;2DGraphics
    { N_("RasterGraphics"), "folder", (const char**) &Graphics2DGraphics},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Audio or Video or AudioVideo
    { N_("Recorder"), "folder", (const char**) &AudioorVideoorAudioVideo},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("RemoteAccess"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("RevisionControl"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Robotics"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("RolePlaying"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics
    { N_("Scanning"), "folder", (const char**) &Graphics},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Science"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Screensavers"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Settings or System
    { N_("Security"), "folder", (const char**) &SettingsorSystem},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo;Audio
    { N_("Sequencer"), "folder", (const char**) &AudioVideoAudio},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Settings"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("Shooter"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("Simulation"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science or Utility
    { N_("Spirituality"), "folder", (const char**) &EducationorScienceorUtility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Education or Science
    { N_("Sports"), "folder", (const char**) &EducationorScience},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("SportsGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("Spreadsheet"), "folder", (const char**) &Office},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Game
    { N_("StrategyGame"), "folder", (const char**) &Game},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("System"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo;Video
    { N_("TV"), "folder", (const char**) &AudioVideoVideo},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("Telephony"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility
    { N_("TelephonyTools"), "folder", (const char**) &Utility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: System
    { N_("TerminalEmulator"), "folder", (const char**) &System},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility
    { N_("TextEditor"), "folder", (const char**) &Utility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Utility
    { N_("TextTools"), "folder", (const char**) &Utility},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Development
    { N_("Translation"), "folder", (const char**) &Development},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: AudioVideo;Audio
    { N_("Tuner"), "folder", (const char**) &AudioVideoAudio},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Utility"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics;2DGraphics
    { N_("VectorGraphics"), "folder", (const char**) &Graphics2DGraphics},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("Video"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("VideoConference"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Graphics or Office
    { N_("Viewer"), "folder", (const char**) &GraphicsorOffice},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes.
    { N_("WINE"), "folder", (const char**) nullptr},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network
    { N_("WebBrowser"), "folder", (const char**) &Network},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Network or Development
    { N_("WebDevelopment"), "folder", (const char**) &NetworkorDevelopment},
// TRANSLATORS: This is a menu category name from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry . Please add spaces as needed but no double-quotes. Context: Office
    { N_("WordProcessor"), "folder", (const char**) &Office}
};
}
